# Generated by Django 4.1.4 on 2023-06-17 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='houseloc',
            new_name='latitude',
        ),
        migrations.AddField(
            model_name='owner',
            name='longitude',
            field=models.CharField(default='83.98629856004847', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='owner',
            name='newrequest',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
